# Generated by Django 3.2.8 on 2021-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-image-placeholder.png', upload_to='images/profile/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Earth', max_length=20),
        ),
    ]
