# Generated by Django 3.2.5 on 2021-07-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.ImageField(blank=True, default='profile-image-placeholder.png', null=True, upload_to='images/profile/%Y/%m/', verbose_name='Image'),
        ),
    ]
