# Generated by Django 3.2 on 2022-04-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skit', '0002_alter_skit_content'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='skit.Tag')),
            ],
        ),
    ]
