# Generated by Django 3.2.5 on 2021-07-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Earth', max_length=220, null=True),
        ),
    ]
