# Generated by Django 3.2.6 on 2021-08-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.ImageField(default='profile-image-placeholder.png', upload_to='images/profile/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Earth', max_length=20),
        ),
    ]
