# Generated by Django 3.2.6 on 2021-08-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210813_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_url',
            new_name='image',
        ),
    ]
