# Generated by Django 3.2 on 2022-03-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0003_textz_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textz',
            name='document',
        ),
    ]
