# Generated by Django 3.2 on 2022-04-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0004_remove_textz_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=5)),
                ('_date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
