# Generated by Django 3.2 on 2022-04-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0008_alter_passcode_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcode',
            name='used_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
