# Generated by Django 3.2 on 2022-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0009_passcode_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcode',
            name='transactionId',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
