# Generated by Django 3.2 on 2022-07-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0010_passcode_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='textz',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='expo.document'),
        ),
    ]
