# Generated by Django 3.2 on 2024-01-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0013_auto_20231110_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passcode',
            old_name='passcode',
            new_name='code',
        ),
    ]
