# Generated by Django 3.2.5 on 2021-08-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_full_name',
            field=models.BooleanField(default=True, verbose_name='show_full_name'),
        ),
    ]
