# Generated by Django 3.2.8 on 2021-11-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='E.g example@example.com', max_length=254, verbose_name='email'),
        ),
    ]
