# Generated by Django 3.2.5 on 2021-08-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_show_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='show_full_name',
            new_name='is_show_full_name',
        ),
    ]
