# Generated by Django 3.2.5 on 2021-08-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_show_full_name_user_is_show_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_show_full_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
