# Generated by Django 3.2.5 on 2021-07-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skit',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/post/%Y/%m/', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='skit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='skit',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/post/%Y/%m/', verbose_name='Video'),
        ),
    ]
