# Generated by Django 3.2.5 on 2021-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skit', '0002_auto_20210727_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skit',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
