# Generated by Django 3.2.5 on 2021-07-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skit', '0003_alter_skit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skit',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
