# Generated by Django 3.2.5 on 2021-07-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skit', '0004_alter_skit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skit',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
