# Generated by Django 3.2.8 on 2021-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('skitte_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(blank=True, to='skitte_chat.PublicRoomChatMessage')),
                ('participants', models.ManyToManyField(blank=True, related_name='chats', to='profiles.Profile')),
            ],
        ),
    ]
