# Generated by Django 3.2.8 on 2022-01-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('skitte_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='user who are admin', related_name='room_admin', to='profiles.Profile'),
        ),
    ]
