# Generated by Django 3.2.8 on 2021-11-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitte_chat', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, to='skitte_chat.PublicRoomChatMessage'),
        ),
    ]
