# Generated by Django 3.2.8 on 2021-11-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('skitte_chat', '0004_auto_20211126_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='user who are online', related_name='chats', to='profiles.Profile'),
        ),
    ]
