# Generated by Django 3.2.8 on 2021-12-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitte_chat', '0007_auto_20211126_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skitte-images/group/%Y/%m/', verbose_name='Image'),
        ),
    ]
